### ISSUE TITLE
Ctrl+W shortcut for closing windows doesn't work

### ISSUE THREAD

**Issue by teaecetyrannis** [RVirmoors/maxhotkey-pd#1]
Simply that.
The shortcut Ctrl+N to create a new window works, but Ctrl+W doesn't seem to work.
When using the shortcut, a [warp~] object was created. I deleted "w" from the maxhotkey.cfg key bindings and it still doesn't work.

I'm using pd 0.52-2 (vanilla) with no other plugins other than pd_deken.tcl (which comes with vanilla).

**Comment by RVirmoors** [comment]
thanks for spotting it! easy fix: i had a leftover `bind all <$::modifier-Key-w> {}` in the .tcl file
i never use this shortcut, so that's why i'd left it in
